{"name": "Проверка неудачной авторизации с корявыми данными", "status": "passed", "steps": [{"name": "Логин существующего пользователя", "status": "passed", "parameters": [{"name": "user_data", "value": "{'email': '123123123', 'password': '123123123'}"}], "start": 1715922530289, "stop": 1715922530536}], "start": 1715922530289, "stop": 1715922530537, "uuid": "9f770be8-fbad-4565-a8e8-23780f75afa0", "historyId": "d27f5161b3ac0fb0c00ff6698956a1fb", "testCaseId": "d27f5161b3ac0fb0c00ff6698956a1fb", "fullName": "tests.test_user.TestUser#test_login_user_failed", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user"}, {"name": "subSuite", "value": "TestUser"}, {"name": "host", "value": "debian"}, {"name": "thread", "value": "6235-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user"}]}